[project]
name = "loglens"
type = "rust"
root_path = "/home/carlos/personal_projects/LogLens/loglens"
created_at = "2025-10-06T21:24:31.659454647+00:00"

[loglens]
auto_analyze = true
default_provider = "openrouter"
default_level = "ERROR"

[mcp]
enabled = true
